name: Execute SSH Commands

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run SSH Commands
      id: ssh
      uses: arthurvanl/action-exec-ssh@v1
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.PASSWORD }}
        ssh_1: 'pm2 list'
        ssh_2: 'pm2 restart 0'
        ssh_3: 'pm2 list'